/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author ASUS
 */
public class BiodataFrame extends javax.swing.JFrame {

    private final String[] EDUCATION_LEVELS = { "SD", "SMP", "SMA", "D1", "D2", "D3", "D4/S1", "S2", "S3" };
    private final double MINIMUM_IPK = 3.01;
    private final int MINIMUM_EDUCATION_INDEX = 3;

    /**
     * Creates new form BiodataFrame
     */
    public BiodataFrame() {
        initComponents();
        setupValidations();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        genderGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        bacaCheckBox = new javax.swing.JCheckBox();
        makanCheckBox = new javax.swing.JCheckBox();
        nikText = new javax.swing.JTextField();
        namaText = new javax.swing.JTextField();
        lakiRadioButton = new javax.swing.JRadioButton();
        perempuanRadioButton = new javax.swing.JRadioButton();
        pendidikanComboBox = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        daftarButton = new javax.swing.JButton();
        tidurCheckBox = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        alamatText = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        tglLahirText = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        telpText = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        ipkText = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("NIK");

        jLabel2.setText("Nama");

        jLabel3.setText("Pendidikan");

        jLabel4.setText("Gender");

        jLabel5.setText("Hobi");

        bacaCheckBox.setText("membaca");

        makanCheckBox.setText("Makan");

        namaText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaTextActionPerformed(evt);
            }
        });

        genderGroup.add(lakiRadioButton);
        lakiRadioButton.setText("Laki-laki");
        lakiRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lakiRadioButtonActionPerformed(evt);
            }
        });

        genderGroup.add(perempuanRadioButton);
        perempuanRadioButton.setText("Perempuan");

        pendidikanComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(
                new String[] { "SD", "SMP", "SMA", "D1", "D2", "D3", "D4/S1", "S2", "S3" }));
        pendidikanComboBox.setSelectedIndex(-1);

        jLabel6.setText("Alamat");

        daftarButton.setText("Daftar");
        daftarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daftarButtonActionPerformed(evt);
            }
        });

        tidurCheckBox.setText("Tidur");

        alamatText.setColumns(20);
        alamatText.setRows(5);
        jScrollPane1.setViewportView(alamatText);

        jLabel7.setText("Tanggal Lahir");

        jLabel8.setText("No Telp");

        telpText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telpTextActionPerformed(evt);
            }
        });

        jLabel9.setText("IPK");

        ipkText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ipkTextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout
                                                                .createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                        false)
                                                                .addComponent(jLabel1,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        Short.MAX_VALUE)
                                                                .addComponent(jLabel2,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        Short.MAX_VALUE)
                                                                .addComponent(jLabel5,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        Short.MAX_VALUE)
                                                                .addComponent(jLabel6,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE, 58,
                                                                        Short.MAX_VALUE))
                                                        .addComponent(jLabel7)
                                                        .addComponent(jLabel8))
                                                .addGap(23, 23, 23)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout
                                                                .createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                        false)
                                                                .addComponent(daftarButton)
                                                                .addComponent(jScrollPane1,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(makanCheckBox,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 85,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(bacaCheckBox,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 85,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(nikText,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE, 270,
                                                                        Short.MAX_VALUE)
                                                                .addComponent(namaText)
                                                                .addComponent(tglLahirText))
                                                        .addComponent(tidurCheckBox,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 85,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(telpText, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                270, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout
                                                                .createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                        false)
                                                                .addComponent(jLabel3,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        Short.MAX_VALUE)
                                                                .addComponent(jLabel4,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        Short.MAX_VALUE))
                                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(37, 37, 37)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                false)
                                                        .addComponent(pendidikanComboBox,
                                                                javax.swing.GroupLayout.Alignment.LEADING, 0, 270,
                                                                Short.MAX_VALUE)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout
                                                                .createSequentialGroup()
                                                                .addComponent(lakiRadioButton,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 98,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(perempuanRadioButton,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 98,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(ipkText,
                                                                javax.swing.GroupLayout.Alignment.LEADING))))
                                .addGap(0, 25, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(22, 22, 22)
                                                .addComponent(jLabel1))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(16, 16, 16)
                                                .addComponent(nikText, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(namaText, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7)
                                        .addComponent(tglLahirText, javax.swing.GroupLayout.PREFERRED_SIZE, 28,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel8)
                                        .addComponent(telpText, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(pendidikanComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(ipkText, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel9))
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lakiRadioButton)
                                        .addComponent(perempuanRadioButton)
                                        .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel5)
                                        .addComponent(bacaCheckBox))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(makanCheckBox)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tidurCheckBox)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addComponent(daftarButton)
                                .addGap(17, 17, 17)));

        lakiRadioButton.setActionCommand("Laki-laki");
        perempuanRadioButton.setActionCommand("Perempuan");

        pack();
    }// </editor-fold>

    private void setupValidations() {
        // Setup phone number validation - only numbers allowed
        telpText.addKeyListener(new KeyAdapter() {
            @Override
            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();
                if (!Character.isDigit(c)) {
                    e.consume();
                }
            }
        });

        try {
            MaskFormatter dateFormatter = new MaskFormatter("####-##-##");
            dateFormatter.setPlaceholderCharacter('_');
            JFormattedTextField dateField = new JFormattedTextField(dateFormatter);
            dateField.setBounds(tglLahirText.getBounds());
            this.remove(tglLahirText);
            this.add(dateField);
            tglLahirText = dateField;
        } catch (ParseException e) {
            e.printStackTrace();
        }

        // Setup IPK formatter
        try {
            MaskFormatter ipkFormatter = new MaskFormatter("#.##");
            ipkFormatter.setPlaceholderCharacter('_');
            JFormattedTextField ipkField = new JFormattedTextField(ipkFormatter);
            ipkField.setBounds(ipkText.getBounds());
            this.remove(ipkText);
            this.add(ipkField);
            ipkText = ipkField;
        } catch (ParseException e) {
            e.printStackTrace();
        }
    }

    private boolean validateAge() {
        try {
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            Date birthDate = sdf.parse(tglLahirText.getText());
            Calendar dob = Calendar.getInstance();
            dob.setTime(birthDate);
            Calendar today = Calendar.getInstance();

            int age = today.get(Calendar.YEAR) - dob.get(Calendar.YEAR);
            if (today.get(Calendar.MONTH) < dob.get(Calendar.MONTH) ||
                    (today.get(Calendar.MONTH) == dob.get(Calendar.MONTH) &&
                            today.get(Calendar.DAY_OF_MONTH) < dob.get(Calendar.DAY_OF_MONTH))) {
                age--;
            }

            if (age < 18) {
                JOptionPane.showMessageDialog(this,
                        "Anda belum cukup umur untuk melamar pekerjaan ini",
                        "Peringatan",
                        JOptionPane.WARNING_MESSAGE);
                return false;
            }
            return true;
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(this,
                    "Format tanggal lahir tidak valid (YYYY-MM-DD)",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            return false;
        }
    }

    private boolean validateIPK() {
        try {
            double ipk = Double.parseDouble(ipkText.getText());
            if (ipk < 0.00 || ipk > 4.00) {
                JOptionPane.showMessageDialog(this,
                        "IPK tidak valid",
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
                return false;
            }
            if (ipk < MINIMUM_IPK) {
                JOptionPane.showMessageDialog(this,
                        "IPK minimum yang dibutuhkan adalah 3,01",
                        "Peringatan",
                        JOptionPane.WARNING_MESSAGE);
                return false;
            }
            return true;
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                    "IPK tidak valid",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            return false;
        }
    }

    private boolean validateEducation() {
        int selectedIndex = pendidikanComboBox.getSelectedIndex();
        String selectedEducation = (String) pendidikanComboBox.getSelectedItem();

        // Find the index of selected education in our ordered array
        int educationLevel = -1;
        for (int i = 0; i < EDUCATION_LEVELS.length; i++) {
            if (EDUCATION_LEVELS[i].equals(selectedEducation)) {
                educationLevel = i;
                break;
            }
        }

        if (educationLevel < MINIMUM_EDUCATION_INDEX) {
            JOptionPane.showMessageDialog(this,
                    "Pendidikan minimal yang dibutuhkan adalah D1",
                    "Peringatan",
                    JOptionPane.WARNING_MESSAGE);
            return false;
        }
        return true;
    }

    private boolean validateForm() {
        // Check if all required fields are filled
        if (nikText.getText().trim().isEmpty() ||
                namaText.getText().trim().isEmpty() ||
                tglLahirText.getText().trim().isEmpty() ||
                telpText.getText().trim().isEmpty() ||
                pendidikanComboBox.getSelectedIndex() == -1 ||
                ipkText.getText().trim().isEmpty() ||
                genderGroup.getSelection() == null ||
                alamatText.getText().trim().isEmpty()) {

            JOptionPane.showMessageDialog(this,
                    "Semua field harus diisi",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            return false;
        }

        return validateAge() && validateIPK() && validateEducation();
    }

    private void clearForm() {
        nikText.setText("");
        namaText.setText("");
        tglLahirText.setText("");
        telpText.setText("");
        pendidikanComboBox.setSelectedIndex(-1);
        ipkText.setText("");
        genderGroup.clearSelection();
        bacaCheckBox.setSelected(false);
        makanCheckBox.setSelected(false);
        tidurCheckBox.setSelected(false);
        alamatText.setText("");
    }

    private void daftarButtonActionPerformed(java.awt.event.ActionEvent evt) {
        if (validateForm()) {
            JOptionPane.showMessageDialog(this,
                    "Anda berhasil mendaftar",
                    "Sukses",
                    JOptionPane.INFORMATION_MESSAGE);
            clearForm();
        }
    }

    private void namaTextActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void lakiRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void telpTextActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void ipkTextActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BiodataFrame.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BiodataFrame.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BiodataFrame.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BiodataFrame.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BiodataFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JTextArea alamatText;
    private javax.swing.JCheckBox bacaCheckBox;
    private javax.swing.JButton daftarButton;
    private javax.swing.ButtonGroup genderGroup;
    private javax.swing.JTextField ipkText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton lakiRadioButton;
    private javax.swing.JCheckBox makanCheckBox;
    private javax.swing.JTextField namaText;
    private javax.swing.JTextField nikText;
    private javax.swing.JComboBox<String> pendidikanComboBox;
    private javax.swing.JRadioButton perempuanRadioButton;
    private javax.swing.JTextField telpText;
    private javax.swing.JTextField tglLahirText;
    private javax.swing.JCheckBox tidurCheckBox;
    // End of variables declaration
}
